
{
    "admin_password": "${CC_ADMIN_PASSWORD}",
    "admin_user": "ccadmin",
    "api": "api.127-0-0-1.nip.io",
    "apps_domain": "apps.127-0-0-1.nip.io",
    "internal_cc_address": "internal-service",
    "skip_ssl_validation": true,
    "timeout_scale": 2,
    "use_http": false,

    "include_app_syslog_tcp": false,
    "include_apps": false,
    "include_cnb": true,
    "include_container_networking": false,
    "include_deployments": false,
    "include_detect": false,
    "include_docker": false,
    "include_file_based_service_bindings": true,
    "include_http2_routing": false,
    "include_internet_dependent": false,
    "include_ipv6": false,
    "include_isolation_segments": false,
    "include_private_docker_registry": false,
    "include_route_services": false,
    "include_routing": false,
    "include_routing_isolation_segments": false,
    "include_security_groups": false,
    "include_service_discovery": false,
    "include_service_instance_sharing": false,
    "include_services": false,
    "include_ssh": false,
    "include_sso": false,
    "include_tasks": false,
    "include_tcp_routing": false,
    "include_user_provided_services": false,
    "include_tcp_isolation_segments": false,
    "include_v3": false,
    "include_volume_services": false,
    "include_windows": false,
    "include_zipkin": false,

    "java_buildpack_name": "java-buildpack",
    "ruby_buildpack_name": "ruby_buildpack",
    "nodejs_buildpack_name": "nodejs_buildpack",
    "binary_buildpack_name": "binary_buildpack",
    "go_buildpack_name": "go_buildpack",
    "python_buildpack_name": "python_buildpack",
}
