name: E2E Tests on KinD

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set kernel settings
        run: |
          docker run --rm \
            --privileged \
            --pid host \
            -v /lib/modules:/lib/modules:ro \
            alpine sh -c "sysctl -w fs.inotify.max_user_instances=512 && modprobe nfs && modprobe nfsd"
      - name: Install dependencies
        run: |
          mkdir -p $HOME/.local/bin && echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          curl -L https://kind.sigs.k8s.io/dl/v${KIND_VERSION}/kind-linux-amd64 -o $HOME/.local/bin/kind
          chmod +x $HOME/.local/bin/kind
          curl -L https://github.com/helmfile/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz | tar -zx
          mv helmfile $HOME/.local/bin/helmfile
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=${CF_CLI_VERSION}&source=github" | tar -zx
          mv cf8 $HOME/.local/bin/cf
          curl -L "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl" -o $HOME/.local/bin/kubectl
          chmod +x $HOME/.local/bin/kubectl
        env:
          CF_CLI_VERSION: "8.18.0"
          KIND_VERSION: "0.31.0"
          HELMFILE_VERSION: "1.4.3"
          KUBECTL_VERSION: "1.28.0"
      - name: setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false
      - name: checkout kind-deployment
        uses: actions/checkout@v6
        with:
          repository: "cloudfoundry/kind-deployment"
          path: "kind"
      - name: Run make up
        run: |
          cd kind && make up
      - name: Login
        run: cd kind && make login
      - name: Init
        run: cd kind && make bootstrap-complete
      - name: Update cnb_app_lifecycle.tgz in cluster
        run: |
          make build
          kubectl -n cf-system rollout status deployment fileserver
          POD=cf-system/$(kubectl get pod -n cf-system -l app.kubernetes.io/name=fileserver -o jsonpath='{.items[0].metadata.name}')

          mkdir lifecycle
          kubectl cp $POD:fileserver/v1/static/cnb_app_lifecycle/cnb_app_lifecycle.tgz cnb_app_lifecycle_original.tgz
          tar xf cnb_app_lifecycle_original.tgz -C lifecycle
          cp bin/* lifecycle
          tar czf cnb_app_lifecycle_updated.tgz -C lifecycle .

          kubectl cp cnb_app_lifecycle_updated.tgz $POD:fileserver/v1/static/cnb_app_lifecycle/cnb_app_lifecycle.tgz
      - name: Run E2E tests for java
        run: |
          cf push hello-java -f examples/hello-java/manifest.yaml
          curl -s -f hello-java.apps.127-0-0-1.nip.io | grep -F "Hello World"
          cf delete hello-java -f -r
      - name: Run E2E tests for nodejs
        run: |
          cf push hello-js -f examples/hello-js/manifest.yaml
          curl -s -f hello-js.apps.127-0-0-1.nip.io | grep -F "Hello World"
          cf delete hello-js -f -r
