name: E2E Tests on KinD

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cloudfoundry/kind-deployment/.github/actions/setup-cf@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build cnbapplifecycle.tgz
        run: make copy-binaries package
      - name: Load updated cnbapplifecycle.tgz into kind
        run: |
          kubectl cp bin/cnb_app_lifecycle.tgz \
          cf-system/$(kubectl get pod -n cf-system -l app.kubernetes.io/name=fileserver \
          -o jsonpath='{.items[0].metadata.name}'):fileserver/v1/static/cnb_app_lifecycle/cnb_app_lifecycle.tgz
      - name: Run E2E tests for java
        run: |
          cf push hello-java -f examples/hello-java/manifest.yaml
          curl -s -f hello-java.apps.127-0-0-1.nip.io | grep -F "Hello World"
          cf delete hello-java -f -r
      - name: Run E2E tests for nodejs
        run: |
          cf push hello-js -f examples/hello-js/manifest.yaml
          curl -s -f hello-js.apps.127-0-0-1.nip.io | grep -F "Hello World"
          cf delete hello-js -f -r
      