name: CF Acceptance Tests on KinD

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  kind-cats:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: cloudfoundry/kind-deployment/.github/actions/setup-cf@v0.25.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build cnbapplifecycle.tgz
        run: make copy-binaries package
      - name: Load updated cnbapplifecycle.tgz into kind
        run: |
          kubectl cp bin/cnb_app_lifecycle.tgz \
          cf-system/$(kubectl get pod -n cf-system -l app.kubernetes.io/name=fileserver \
          -o jsonpath='{.items[0].metadata.name}'):fileserver/v1/static/cnb_app_lifecycle/cnb_app_lifecycle.tgz
      - uses: cloudfoundry/kind-deployment/.github/actions/setup-cf-tests@v0.25.0
        with:
          test-repo: cf-acceptance-tests
          config-template: ${{ github.workspace }}/.github/cats-config.tpl
          config-output: ${{ github.workspace }}/.github/cats-config.json
      - name: run CATS
        env:
          CONFIG: "${{ github.workspace }}/.github/cats-config.json"
          GINKGO_NO_COLOR: "true"
        run: |
          ./cf-acceptance-tests/bin/test --no-color --github-output --timeout=180m --procs=4 --flake-attempts=2 --json-report report.json
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: report
          path: ./cf-acceptance-tests/report.json
